CREATE DATABASE IF NOT EXISTS quiz_db;

USE quiz_db;

CREATE TABLE IF NOT EXISTS quiz (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question TEXT NOT NULL,
    option_1 TEXT NOT NULL,
    option_2 TEXT NOT NULL,
    option_3 TEXT NOT NULL,
    option_4 TEXT NOT NULL,
    correct_number INT NOT NULL
);

INSERT INTO quiz (question, option_1, option_2, option_3, option_4, correct_number) VALUES
('Quem ganhou a Copa do Mundo FIFA de 2018?', 'Alemanha', 'Brasil', 'França', 'Argentina', 3),
('Qual jogador marcou mais gols em Copas do Mundo?', 'Pelé', 'Ronaldo', 'Miroslav Klose', 'Cristiano Ronaldo', 3),
('Qual é o clube de futebol mais antigo do mundo?', 'Real Madrid', 'Sheffield FC', 'Liverpool FC', 'Manchester United', 2),
('Qual país sediou a primeira Copa do Mundo?', 'Brasil', 'Itália', 'Uruguai', 'Alemanha', 3),
('Qual jogador ganhou mais Bolas de Ouro?', 'Lionel Messi', 'Cristiano Ronaldo', 'Michel Platini', 'Johan Cruyff', 1),
('Quantos títulos da Liga dos Campeões o Real Madrid conquistou até 2023?', '10', '13', '14', '16', 3),
('Quem é o maior artilheiro da história do Campeonato Brasileiro?', 'Romário', 'Pelé', 'Roberto Dinamite', 'Zico', 3),
('Qual jogador é conhecido como "El Fenómeno"?', 'Lionel Messi', 'Cristiano Ronaldo', 'Ronaldinho Gaúcho', 'Ronaldo', 4),
('Quem marcou o gol da vitória do Brasil na final da Copa do Mundo de 1994?', 'Romário', 'Bebeto', 'Dunga', 'Nenhum, foi nos pênaltis', 4),
('Qual é o único país a participar de todas as Copas do Mundo?', 'Brasil', 'Alemanha', 'Argentina', 'Itália', 1),
('Quem foi o técnico do Brasil na Copa do Mundo de 2002?', 'Felipão', 'Zagallo', 'Parreira', 'Dunga', 1),
('Qual é o estádio de futebol mais antigo do Brasil?', 'Maracanã', 'Morumbi', 'Pacaembu', 'São Januário', 3),
('Quantos gols Pelé marcou em sua carreira?', '1000', '1281', '1250', '1350', 2),
('Qual clube ganhou a Libertadores da América em 2019?', 'Boca Juniors', 'River Plate', 'Flamengo', 'Grêmio', 3),
('Quem é conhecido como "O Rei do Futebol"?', 'Diego Maradona', 'Lionel Messi', 'Pelé', 'Zico', 3),
('Qual seleção ganhou a Copa do Mundo de 1966?', 'Brasil', 'Inglaterra', 'Alemanha', 'Argentina', 2),
('Qual jogador marcou o gol do título da Alemanha na final da Copa do Mundo de 2014?', 'Miroslav Klose', 'Thomas Müller', 'Mario Götze', 'Toni Kroos', 3),
('Quem foi o técnico do Barcelona durante a era "Pep Team"?', 'Pep Guardiola', 'José Mourinho', 'Luis Enrique', 'Frank Rijkaard', 1),
('Quantos títulos da Liga dos Campeões da UEFA o Barcelona conquistou até 2023?', '3', '4', '5', '6', 3),
('Qual jogador é conhecido como "La Pulga"?', 'Cristiano Ronaldo', 'Lionel Messi', 'Sergio Agüero', 'Diego Maradona', 2),
('Qual é o time com mais títulos do Campeonato Brasileiro até 2023?', 'Palmeiras', 'Corinthians', 'Flamengo', 'São Paulo', 1),
('Qual foi o placar da final da Copa do Mundo de 1950 entre Brasil e Uruguai?', '1-0', '1-1', '2-1 para o Uruguai', '2-2', 3),
('Quem foi o técnico da seleção brasileira na Copa do Mundo de 1982?', 'Telê Santana', 'Zagallo', 'Carlos Alberto Parreira', 'Dunga', 1),
('Qual seleção foi campeã da Copa América em 2021?', 'Brasil', 'Argentina', 'Uruguai', 'Chile', 2),
('Qual jogador é conhecido como "Il Fenomeno"?', 'Zinedine Zidane', 'Lionel Messi', 'Ronaldo', 'Ronaldinho Gaúcho', 3),
('Quem marcou o gol do título do Palmeiras na Libertadores 2021?', 'Deyverson', 'Gabriel Veron', 'Rony', 'Raphael Veiga', 1),
('Qual clube foi o primeiro campeão da Copa Libertadores da América?', 'Peñarol', 'Santos', 'Boca Juniors', 'River Plate', 1),
('Qual jogador tem o recorde de gols em uma única edição da Copa do Mundo?', 'Pelé', 'Just Fontaine', 'Gerd Müller', 'Ronaldo', 2),
('Qual seleção venceu a primeira Eurocopa, em 1960?', 'Espanha', 'Alemanha', 'França', 'União Soviética', 4),
('Quem foi o artilheiro da Copa do Mundo de 1998?', 'Gabriel Batistuta', 'Davor Šuker', 'Ronaldo', 'Christian Vieri', 2),
('Qual foi o placar da final da Liga dos Campeões da UEFA 2005 entre Milan e Liverpool?', '3-2 para o Milan', '3-3, Liverpool venceu nos pênaltis', '2-2, Milan venceu nos pênaltis', '4-3 para o Liverpool', 2),
('Quem foi eleito o melhor jogador do mundo pela FIFA em 2004?', 'Ronaldinho Gaúcho', 'Zinedine Zidane', 'Thierry Henry', 'Cristiano Ronaldo', 1),
('Qual seleção venceu a Copa do Mundo de 1986?', 'Itália', 'Alemanha', 'Argentina', 'Brasil', 3),
('Quem foi o artilheiro da Copa do Mundo de 2014?', 'Lionel Messi', 'Neymar', 'Thomas Müller', 'James Rodríguez', 4),
('Qual jogador brasileiro é conhecido como "O Anjo das Pernas Tortas"?', 'Garrincha', 'Zico', 'Rivelino', 'Romário', 1),
('Qual foi o placar da final da Copa do Mundo de 2018 entre França e Croácia?', '2-1', '3-1', '4-2 para a França', '3-2 para a Croácia', 3),
('Qual seleção tem mais títulos da Copa América até 2023?', 'Brasil', 'Uruguai', 'Argentina', 'Chile', 2),
('Quem foi o capitão da seleção brasileira na conquista do pentacampeonato em 2002?', 'Cafu', 'Ronaldo', 'Roberto Carlos', 'Rivaldo', 1);


-- INSERT INTO quiz (question, option_1, option_2, option_3, option_4, correct_number) VALUES
-- ('Qual é a capital da França?', 'Berlim', 'Madri', 'Paris', 'Roma', 3),
-- ('Qual planeta é conhecido como o Planeta Vermelho?', 'Terra', 'Marte', 'Júpiter', 'Vênus', 2),
-- ('Qual é o maior mamífero?', 'Elefante', 'Baleia', 'Tubarão', 'Dinossauro', 2),
-- ('Qual é o menor número primo?', '1', '2', '3', '5', 2),
-- ('Em que ano terminou a Segunda Guerra Mundial?', '1941', '1942', '1944', '1945', 4),
-- ('Qual é o ponto de ebulição da água?', '90°C', '100°C', '110°C', '120°C', 2),
-- ('Qual é o símbolo químico do ouro?', 'Au', 'Ag', 'Fe', 'Pb', 1),
-- ('Quem escreveu "Hamlet"?', 'Charles Dickens', 'William Shakespeare', 'Mark Twain', 'Jane Austen', 2),
-- ('Qual é a velocidade da luz?', '299.792 km/s', '300.000 km/s', '150.000 km/s', '1.000.000 km/s', 1),
-- ('Qual elemento tem o número atômico 1?', 'Hélio', 'Oxigênio', 'Hidrogênio', 'Carbono', 3),
-- ('Qual é o maior oceano?', 'Atlântico', 'Índico', 'Ártico', 'Pacífico', 4),
-- ('Qual é o principal ingrediente do guacamole?', 'Tomate', 'Batata', 'Abacate', 'Cebola', 3),
-- ('Quem pintou a Mona Lisa?', 'Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Claude Monet', 3),
-- ('Qual é a capital do Japão?', 'Pequim', 'Tóquio', 'Seul', 'Bangkok', 2),
-- ('Qual órgão bombeia sangue pelo corpo?', 'Fígado', 'Cérebro', 'Coração', 'Pulmão', 3),
-- ('Qual é a língua mais falada no mundo?', 'Espanhol', 'Inglês', 'Mandarim', 'Hindi', 3),
-- ('Qual país é conhecido como a Terra do Sol Nascente?', 'China', 'Coreia do Sul', 'Índia', 'Japão', 4),
-- ('Quem desenvolveu a teoria da relatividade?', 'Isaac Newton', 'Galileu Galilei', 'Albert Einstein', 'Nikola Tesla', 3),
-- ('Qual é a substância natural mais dura?', 'Ouro', 'Ferro', 'Diamante', 'Platina', 3),
-- ('Qual é o menor país do mundo?', 'Mônaco', 'Vaticano', 'San Marino', 'Liechtenstein', 2),
-- ('Qual é o rio mais longo do mundo?', 'Amazonas', 'Nilo', 'Yangtzé', 'Mississippi', 2),
-- ('Quem foi o primeiro homem a pisar na lua?', 'Yuri Gagarin', 'Buzz Aldrin', 'Neil Armstrong', 'Michael Collins', 3),
-- ('Qual é o maior deserto do mundo?', 'Saara', 'Gobi', 'Ártico', 'Antártico', 1),
-- ('Qual é a capital do Canadá?', 'Toronto', 'Vancouver', 'Montreal', 'Ottawa', 4),
-- ('Quem descobriu a penicilina?', 'Marie Curie', 'Alexander Fleming', 'Louis Pasteur', 'Joseph Lister', 2),
-- ('Qual é o menor planeta do nosso sistema solar?', 'Marte', 'Terra', 'Mercúrio', 'Vênus', 3),
-- ('Qual é o maior continente?', 'África', 'Ásia', 'Europa', 'Austrália', 2),
-- ('Qual é o maior osso do corpo humano?', 'Crânio', 'Fêmur', 'Costela', 'Úmero', 2),
-- ('Qual é o menor oceano?', 'Atlântico', 'Índico', 'Ártico', 'Pacífico', 3),
-- ('Qual é a capital da Austrália?', 'Sydney', 'Melbourne', 'Perth', 'Canberra', 4),
-- ('Qual gás é mais abundante na atmosfera da Terra?', 'Oxigênio', 'Dióxido de Carbono', 'Nitrogênio', 'Hidrogênio', 3),
-- ('Qual é o animal terrestre mais rápido?', 'Leão', 'Guepardo', 'Leopardo', 'Tigre', 2),
-- ('Quem inventou o telefone?', 'Alexander Graham Bell', 'Thomas Edison', 'Nikola Tesla', 'Guglielmo Marconi', 1),
-- ('Qual planeta está mais próximo do Sol?', 'Terra', 'Vênus', 'Mercúrio', 'Marte', 3),
-- ('Qual é a montanha mais alta do mundo?', 'K2', 'Kangchenjunga', 'Lhotse', 'Monte Everest', 4),
-- ('Quem é conhecido como o Pai dos Computadores?', 'Charles Babbage', 'Alan Turing', 'John von Neumann', 'Bill Gates', 1),
-- ('Qual país é o maior em área territorial?', 'Estados Unidos', 'China', 'Canadá', 'Rússia', 4),
-- ('Qual é o principal ingrediente do chocolate?', 'Leite', 'Cacau', 'Açúcar', 'Manteiga', 2),
-- ('Qual é o ponto de congelamento da água?', '0°C', '32°F', '100°C', '212°F', 1);
